In [1]:
import pandas as pd
import math
import numpy as np
import matplotlib.pyplot as plt
import time
import datetime

In [3]:
df = pd.read_excel("Book2_yyy.xlsx") #Intraday Data from Bloomberg

df = df.drop([0]) #Drop first row which is a space 
df.index = range(len(df)) #Select the range row for reindex

N = 505 #Total Constituents in the Index Stock S&P500 and 

equity_list = []
for i in range(N):
    equity_list.append(df.iloc[0, i * 3]) #Row 3 of the Book2 file. Append the equity name to the list
print(equity_list) #Check if the output is correct and print its length too
print(len(equity_list))

df = df.drop([0, 1]) #drop the name and date 
df.index = range(len(df)) #reindex 
df = df.drop([len(df) - 1])#drop last value
print(df)


date_list = list(df.iloc[:, 0])
columns = ['Date'] + equity_list

clean_df = pd.DataFrame(np.arange(len(df) * (N+1)).reshape(len(df), N + 1), index=range(len(df)), columns=columns)
clean_df['Date'] = date_list
clean_df.index = date_list
# clean_df = df.iloc[:, [0, 1]]
# clean_df.columns = ['Date', equity_list[0]]
for i in range(505):
    print(equity_list[i])
    right = df.iloc[:, [i * 3, i * 3 + 1]]
    right.columns = ['Date', equity_list[i]]
    right.index = list(right['Date'])
    value = math.nan
    for date in date_list:
        # print(date)
        if date not in right.index:
            clean_df.loc[date, equity_list[i]] = value
        else:
            value = right.loc[date, equity_list[i]]
            clean_df.loc[date, equity_list[i]] = right.loc[date, equity_list[i]]

print(clean_df)
clean_df.to_csv("15_min_clean.csv", index=False)

['A UN Equity', 'AAL UW Equity', 'AAP UN Equity', 'AAPL UW Equity', 'ABBV UN Equity', 'ABC UN Equity', 'ABMD UW Equity', 'ABT UN Equity', 'ACN UN Equity', 'ADBE UW Equity', 'ADI UW Equity', 'ADM UN Equity', 'ADP UW Equity', 'ADS UN Equity', 'ADSK UW Equity', 'AEE UN Equity', 'AEP UN Equity', 'AES UN Equity', 'AET UN Equity', 'AFL UN Equity', 'AGN UN Equity', 'AIG UN Equity', 'AIV UN Equity', 'AIZ UN Equity', 'AJG UN Equity', 'AKAM UW Equity', 'ALB UN Equity', 'ALGN UW Equity', 'ALK UN Equity', 'ALL UN Equity', 'ALLE UN Equity', 'ALXN UW Equity', 'AMAT UW Equity', 'AMD UW Equity', 'AME UN Equity', 'AMG UN Equity', 'AMGN UW Equity', 'AMP UN Equity', 'AMT UN Equity', 'AMZN UW Equity', 'ANET UN Equity', 'ANSS UW Equity', 'ANTM UN Equity', 'AON UN Equity', 'AOS UN Equity', 'APA UN Equity', 'APC UN Equity', 'APD UN Equity', 'APH UN Equity', 'APTV UN Equity', 'ARE UN Equity', 'ARNC UN Equity', 'ATVI UW Equity', 'AVB UN Equity', 'AVGO UW Equity', 'AVY UN Equity', 'AWK UN Equity', 'AXP UN Equity', 'AZO UN Equity', 'BA UN Equity', 'BAC UN Equity', 'BAX UN Equity', 'BBT UN Equity', 'BBY UN Equity', 'BDX UN Equity', 'BEN UN Equity', 'BF/B UN Equity', 'BHF UW Equity', 'BHGE UN Equity', 'BIIB UW Equity', 'BK UN Equity', 'BKNG UW Equity', 'BLK UN Equity', 'BLL UN Equity', 'BMY UN Equity', 'BR UN Equity', 'BRK/B UN Equity', 'BSX UN Equity', 'BWA UN Equity', 'BXP UN Equity', 'C UN Equity', 'CA UW Equity', 'CAG UN Equity', 'CAH UN Equity', 'CAT UN Equity', 'CB UN Equity', 'CBOE UF Equity', 'CBRE UN Equity', 'CBS UN Equity', 'CCI UN Equity', 'CCL UN Equity', 'CDNS UW Equity', 'CELG UW Equity', 'CERN UW Equity', 'CF UN Equity', 'CFG UN Equity', 'CHD UN Equity', 'CHRW UW Equity', 'CHTR UW Equity', 'CI UN Equity', 'CINF UW Equity', 'CL UN Equity', 'CLX UN Equity', 'CMA UN Equity', 'CMCSA UW Equity', 'CME UW Equity', 'CMG UN Equity', 'CMI UN Equity', 'CMS UN Equity', 'CNC UN Equity', 'CNP UN Equity', 'COF UN Equity', 'COG UN Equity', 'COL UN Equity', 'COO UN Equity', 'COP UN Equity', 'COST UW Equity', 'COTY UN Equity', 'CPB UN Equity', 'CPRT UW Equity', 'CRM UN Equity', 'CSCO UW Equity', 'CSX UW Equity', 'CTAS UW Equity', 'CTL UN Equity', 'CTSH UW Equity', 'CTXS UW Equity', 'CVS UN Equity', 'CVX UN Equity', 'CXO UN Equity', 'D UN Equity', 'DAL UN Equity', 'DE UN Equity', 'DFS UN Equity', 'DG UN Equity', 'DGX UN Equity', 'DHI UN Equity', 'DHR UN Equity', 'DIS UN Equity', 'DISCA UW Equity', 'DISCK UW Equity', 'DISH UW Equity', 'DLR UN Equity', 'DLTR UW Equity', 'DOV UN Equity', 'DRE UN Equity', 'DRI UN Equity', 'DTE UN Equity', 'DUK UN Equity', 'DVA UN Equity', 'DVN UN Equity', 'DWDP UN Equity', 'DXC UN Equity', 'EA UW Equity', 'EBAY UW Equity', 'ECL UN Equity', 'ED UN Equity', 'EFX UN Equity', 'EIX UN Equity', 'EL UN Equity', 'EMN UN Equity', 'EMR UN Equity', 'EOG UN Equity', 'EQIX UW Equity', 'EQR UN Equity', 'EQT UN Equity', 'ES UN Equity', 'ESRX UW Equity', 'ESS UN Equity', 'ETFC UW Equity', 'ETN UN Equity', 'ETR UN Equity', 'EVRG UN Equity', 'EW UN Equity', 'EXC UN Equity', 'EXPD UW Equity', 'EXPE UW Equity', 'EXR UN Equity', 'F UN Equity', 'FAST UW Equity', 'FB UW Equity', 'FBHS UN Equity', 'FCX UN Equity', 'FDX UN Equity', 'FE UN Equity', 'FFIV UW Equity', 'FIS UN Equity', 'FISV UW Equity', 'FITB UW Equity', 'FL UN Equity', 'FLIR UW Equity', 'FLR UN Equity', 'FLS UN Equity', 'FLT UN Equity', 'FMC UN Equity', 'FOX UW Equity', 'FOXA UW Equity', 'FRT UN Equity', 'FTI UN Equity', 'FTNT UW Equity', 'FTV UN Equity', 'GD UN Equity', 'GE UN Equity', 'GILD UW Equity', 'GIS UN Equity', 'GLW UN Equity', 'GM UN Equity', 'GOOG UW Equity', 'GOOGL UW Equity', 'GPC UN Equity', 'GPN UN Equity', 'GPS UN Equity', 'GRMN UW Equity', 'GS UN Equity', 'GT UW Equity', 'GWW UN Equity', 'HAL UN Equity', 'HAS UW Equity', 'HBAN UW Equity', 'HBI UN Equity', 'HCA UN Equity', 'HCP UN Equity', 'HD UN Equity', 'HES UN Equity', 'HFC UN Equity', 'HIG UN Equity', 'HII UN Equity', 'HLT UN Equity', 'HOG UN Equity', 'HOLX UW Equity', 'HON UN Equity', 'HP UN Equity', 'HPE UN Equity', 'HPQ UN Equity', 'HRB UN Equity', 'HRL UN Equity', 'HRS UN Equity', 'HSIC UW Equity', 'HST UN Equity', 'HSY UN Equity', 'HUM UN Equity', 'IBM UN Equity', 'ICE UN Equity', 'IDXX UW Equity', 'IFF UN Equity', 'ILMN UW Equity', 'INCY UW Equity', 'INFO UW Equity', 'INTC UW Equity', 'INTU UW Equity', 'IP UN Equity', 'IPG UN Equity', 'IPGP UW Equity', 'IQV UN Equity', 'IR UN Equity', 'IRM UN Equity', 'ISRG UW Equity', 'IT UN Equity', 'ITW UN Equity', 'IVZ UN Equity', 'JBHT UW Equity', 'JCI UN Equity', 'JEC UN Equity', 'JEF UN Equity', 'JNJ UN Equity', 'JNPR UN Equity', 'JPM UN Equity', 'JWN UN Equity', 'K UN Equity', 'KEY UN Equity', 'KHC UW Equity', 'KIM UN Equity', 'KLAC UW Equity', 'KMB UN Equity', 'KMI UN Equity', 'KMX UN Equity', 'KO UN Equity', 'KORS UN Equity', 'KR UN Equity', 'KSS UN Equity', 'KSU UN Equity', 'L UN Equity', 'LB UN Equity', 'LEG UN Equity', 'LEN UN Equity', 'LH UN Equity', 'LKQ UW Equity', 'LLL UN Equity', 'LLY UN Equity', 'LMT UN Equity', 'LNC UN Equity', 'LNT UN Equity', 'LOW UN Equity', 'LRCX UW Equity', 'LUV UN Equity', 'LYB UN Equity', 'M UN Equity', 'MA UN Equity', 'MAA UN Equity', 'MAC UN Equity', 'MAR UW Equity', 'MAS UN Equity', 'MAT UW Equity', 'MCD UN Equity', 'MCHP UW Equity', 'MCK UN Equity', 'MCO UN Equity', 'MDLZ UW Equity', 'MDT UN Equity', 'MET UN Equity', 'MGM UN Equity', 'MHK UN Equity', 'MKC UN Equity', 'MLM UN Equity', 'MMC UN Equity', 'MMM UN Equity', 'MNST UW Equity', 'MO UN Equity', 'MOS UN Equity', 'MPC UN Equity', 'MRK UN Equity', 'MRO UN Equity', 'MS UN Equity', 'MSCI UN Equity', 'MSFT UW Equity', 'MSI UN Equity', 'MTB UN Equity', 'MTD UN Equity', 'MU UW Equity', 'MYL UW Equity', 'NBL UN Equity', 'NCLH UN Equity', 'NDAQ UW Equity', 'NEE UN Equity', 'NEM UN Equity', 'NFLX UW Equity', 'NFX UN Equity', 'NI UN Equity', 'NKE UN Equity', 'NKTR UW Equity', 'NLSN UN Equity', 'NOC UN Equity', 'NOV UN Equity', 'NRG UN Equity', 'NSC UN Equity', 'NTAP UW Equity', 'NTRS UW Equity', 'NUE UN Equity', 'NVDA UW Equity', 'NWL UN Equity', 'NWS UW Equity', 'NWSA UW Equity', 'O UN Equity', 'OKE UN Equity', 'OMC UN Equity', 'ORCL UN Equity', 'ORLY UW Equity', 'OXY UN Equity', 'PAYX UW Equity', 'PBCT UW Equity', 'PCAR UW Equity', 'PCG UN Equity', 'PEG UN Equity', 'PEP UW Equity', 'PFE UN Equity', 'PFG UW Equity', 'PG UN Equity', 'PGR UN Equity', 'PH UN Equity', 'PHM UN Equity', 'PKG UN Equity', 'PKI UN Equity', 'PLD UN Equity', 'PM UN Equity', 'PNC UN Equity', 'PNR UN Equity', 'PNW UN Equity', 'PPG UN Equity', 'PPL UN Equity', 'PRGO UN Equity', 'PRU UN Equity', 'PSA UN Equity', 'PSX UN Equity', 'PVH UN Equity', 'PWR UN Equity', 'PX UN Equity', 'PXD UN Equity', 'PYPL UW Equity', 'QCOM UW Equity', 'QRVO UW Equity', 'RCL UN Equity', 'RE UN Equity', 'REG UN Equity', 'REGN UW Equity', 'RF UN Equity', 'RHI UN Equity', 'RHT UN Equity', 'RJF UN Equity', 'RL UN Equity', 'RMD UN Equity', 'ROK UN Equity', 'ROL UN Equity', 'ROP UN Equity', 'ROST UW Equity', 'RSG UN Equity', 'RTN UN Equity', 'SBAC UW Equity', 'SBUX UW Equity', 'SCG UN Equity', 'SCHW UN Equity', 'SEE UN Equity', 'SHW UN Equity', 'SIVB UW Equity', 'SJM UN Equity', 'SLB UN Equity', 'SLG UN Equity', 'SNA UN Equity', 'SNPS UW Equity', 'SO UN Equity', 'SPG UN Equity', 'SPGI UN Equity', 'SRCL UW Equity', 'SRE UN Equity', 'STI UN Equity', 'STT UN Equity', 'STX UW Equity', 'STZ UN Equity', 'SWK UN Equity', 'SWKS UW Equity', 'SYF UN Equity', 'SYK UN Equity', 'SYMC UW Equity', 'SYY UN Equity', 'T UN Equity', 'TAP UN Equity', 'TDG UN Equity', 'TEL UN Equity', 'TGT UN Equity', 'TIF UN Equity', 'TJX UN Equity', 'TMK UN Equity', 'TMO UN Equity', 'TPR UN Equity', 'TRIP UW Equity', 'TROW UW Equity', 'TRV UN Equity', 'TSCO UW Equity', 'TSN UN Equity', 'TSS UN Equity', 'TTWO UW Equity', 'TWTR UN Equity', 'TXN UW Equity', 'TXT UN Equity', 'UA UN Equity', 'UAA UN Equity', 'UAL UW Equity', 'UDR UN Equity', 'UHS UN Equity', 'ULTA UW Equity', 'UNH UN Equity', 'UNM UN Equity', 'UNP UN Equity', 'UPS UN Equity', 'URI UN Equity', 'USB UN Equity', 'UTX UN Equity', 'V UN Equity', 'VAR UN Equity', 'VFC UN Equity', 'VIAB UW Equity', 'VLO UN Equity', 'VMC UN Equity', 'VNO UN Equity', 'VRSK UW Equity', 'VRSN UW Equity', 'VRTX UW Equity', 'VTR UN Equity', 'VZ UN Equity', 'WAT UN Equity', 'WBA UW Equity', 'WCG UN Equity', 'WDC UW Equity', 'WEC UN Equity', 'WELL UN Equity', 'WFC UN Equity', 'WHR UN Equity', 'WLTW UW Equity', 'WM UN Equity', 'WMB UN Equity', 'WMT UN Equity', 'WRK UN Equity', 'WU UN Equity', 'WY UN Equity', 'WYNN UW Equity', 'XEC UN Equity', 'XEL UW Equity', 'XLNX UW Equity', 'XOM UN Equity', 'XRAY UW Equity', 'XRX UN Equity', 'XYL UN Equity', 'YUM UN Equity', 'ZBH UN Equity', 'ZION UW Equity', 'ZTS UN Equity']
505

                    BarTp  Trade  Unnamed: 2              BarTp.1 Trade.1  \
0     2018-04-02 09:30:00  66.92         NaN  2018-04-02 09:30:00   51.41
1     2018-04-02 09:45:00  66.11         NaN  2018-04-02 09:45:00   51.21
2     2018-04-02 10:00:00  65.85         NaN  2018-04-02 10:00:00   50.83
3     2018-04-02 10:15:00  65.82         NaN  2018-04-02 10:15:00   50.78
4     2018-04-02 10:30:00  65.81         NaN  2018-04-02 10:30:00   50.57
...                   ...    ...         ...                  ...     ...
3572  2018-10-15 14:30:00   66.2         NaN  2018-10-15 14:30:00   32.13
3573  2018-10-15 14:45:00   66.2         NaN  2018-10-15 14:45:00   32.18
3574  2018-10-15 15:00:00  65.96         NaN  2018-10-15 15:00:00   32.08
3575  2018-10-15 15:15:00  65.83         NaN  2018-10-15 15:15:00   32.07
3576  2018-10-15 15:30:00  65.88         NaN  2018-10-15 15:30:00   31.98

      Unnamed: 5              BarTp.2 Trade.2  Unnamed: 8  \
0            NaN  2018-04-02 09:30:00  118.13         NaN
1            NaN  2018-04-02 09:45:00  118.05         NaN
2            NaN  2018-04-02 10:00:00  117.13         NaN
3            NaN  2018-04-02 10:15:00  116.51         NaN
4            NaN  2018-04-02 10:30:00  115.97         NaN
...          ...                  ...     ...         ...
3572         NaN  2018-10-15 14:30:00  168.09         NaN
3573         NaN  2018-10-15 14:45:00  168.48         NaN
3574         NaN  2018-10-15 15:00:00  167.75         NaN
3575         NaN  2018-10-15 15:15:00  167.63         NaN
3576         NaN  2018-10-15 15:30:00  167.59         NaN

                  BarTp.3  ... Trade.501  Unnamed: 1505            BarTp.502  \
0     2018-04-02 09:30:00  ...     85.77            NaN  2018-04-02 09:30:00
1     2018-04-02 09:45:00  ...      85.6            NaN  2018-04-02 09:45:00
2     2018-04-02 10:00:00  ...     85.22            NaN  2018-04-02 10:00:00
3     2018-04-02 10:15:00  ...     85.31            NaN  2018-04-02 10:15:00
4     2018-04-02 10:30:00  ...     85.03            NaN  2018-04-02 10:30:00
...                   ...  ...       ...            ...                  ...
3572  2018-10-15 14:30:00  ...        89            NaN                  NaN
3573  2018-10-15 14:45:00  ...     89.06            NaN                  NaN
3574  2018-10-15 15:00:00  ...     88.81            NaN                  NaN
3575  2018-10-15 15:15:00  ...     88.75            NaN                  NaN
3576  2018-10-15 15:30:00  ...      88.8            NaN                  NaN

     Trade.502  Unnamed: 1508            BarTp.503 Trade.503  Unnamed: 1511  \
0       109.29            NaN  2018-04-02 09:30:00     52.55            NaN
1      108.705            NaN  2018-04-02 09:45:00     52.52            NaN
2        108.4            NaN  2018-04-02 10:00:00      52.3            NaN
3       108.32            NaN  2018-04-02 10:15:00     52.13            NaN
4       108.59            NaN  2018-04-02 10:30:00     52.05            NaN
...        ...            ...                  ...       ...            ...
3572       NaN            NaN  2018-10-15 14:30:00     48.27            NaN
3573       NaN            NaN  2018-10-15 14:45:00     48.43            NaN
3574       NaN            NaN  2018-10-15 15:00:00     48.29            NaN
3575       NaN            NaN  2018-10-15 15:15:00     48.26            NaN
3576       NaN            NaN  2018-10-15 15:30:00     48.21            NaN

                BarTp.504 Trade.504
0     2018-04-02 09:30:00     83.09
1     2018-04-02 09:45:00     82.96
2     2018-04-02 10:00:00     82.56
3     2018-04-02 10:15:00     82.51
4     2018-04-02 10:30:00     82.47
...                   ...       ...
3572  2018-10-15 14:30:00     90.52
3573  2018-10-15 14:45:00     90.52
3574  2018-10-15 15:00:00     90.27
3575  2018-10-15 15:15:00     90.04
3576  2018-10-15 15:30:00     90.19

[3577 rows x 1514 columns]
A UN Equity
AAL UW Equity
AAP UN Equity
AAPL UW Equity
ABBV UN Equity
ABC UN Equity
ABMD UW Equity
ABT UN Equity
ACN UN Equity
ADBE UW Equity
ADI UW Equity
ADM UN Equity
ADP UW Equity
ADS UN Equity
ADSK UW Equity
AEE UN Equity
AEP UN Equity
AES UN Equity
AET UN Equity
AFL UN Equity
AGN UN Equity
AIG UN Equity
AIV UN Equity
AIZ UN Equity
AJG UN Equity
AKAM UW Equity
ALB UN Equity
ALGN UW Equity
ALK UN Equity
ALL UN Equity
ALLE UN Equity
ALXN UW Equity
AMAT UW Equity
AMD UW Equity
AME UN Equity
AMG UN Equity
AMGN UW Equity
AMP UN Equity
AMT UN Equity
AMZN UW Equity
ANET UN Equity
ANSS UW Equity
ANTM UN Equity
AON UN Equity
AOS UN Equity
APA UN Equity
APC UN Equity
APD UN Equity
APH UN Equity
APTV UN Equity
ARE UN Equity
ARNC UN Equity
ATVI UW Equity
AVB UN Equity
AVGO UW Equity
AVY UN Equity
AWK UN Equity
AXP UN Equity
AZO UN Equity
BA UN Equity
BAC UN Equity
BAX UN Equity
BBT UN Equity
BBY UN Equity
BDX UN Equity
BEN UN Equity
BF/B UN Equity
BHF UW Equity
BHGE UN Equity
BIIB UW Equity
BK UN Equity
BKNG UW Equity
BLK UN Equity
BLL UN Equity
BMY UN Equity
BR UN Equity
BRK/B UN Equity
BSX UN Equity
BWA UN Equity
BXP UN Equity
C UN Equity
CA UW Equity
CAG UN Equity
CAH UN Equity
CAT UN Equity
CB UN Equity
CBOE UF Equity
CBRE UN Equity
CBS UN Equity
CCI UN Equity
CCL UN Equity
CDNS UW Equity
CELG UW Equity
CERN UW Equity
CF UN Equity
CFG UN Equity
CHD UN Equity
CHRW UW Equity
CHTR UW Equity
CI UN Equity
CINF UW Equity
CL UN Equity
CLX UN Equity
CMA UN Equity
CMCSA UW Equity
CME UW Equity
CMG UN Equity
CMI UN Equity
CMS UN Equity
CNC UN Equity
CNP UN Equity
COF UN Equity
COG UN Equity
COL UN Equity
COO UN Equity
COP UN Equity
COST UW Equity
COTY UN Equity
CPB UN Equity
CPRT UW Equity
CRM UN Equity
CSCO UW Equity
CSX UW Equity
CTAS UW Equity
CTL UN Equity
CTSH UW Equity
CTXS UW Equity
CVS UN Equity
CVX UN Equity
CXO UN Equity
D UN Equity
DAL UN Equity
DE UN Equity
DFS UN Equity
DG UN Equity
DGX UN Equity
DHI UN Equity
DHR UN Equity
DIS UN Equity
DISCA UW Equity
DISCK UW Equity
DISH UW Equity
DLR UN Equity
DLTR UW Equity
DOV UN Equity
DRE UN Equity
DRI UN Equity
DTE UN Equity
DUK UN Equity
DVA UN Equity
DVN UN Equity
DWDP UN Equity
DXC UN Equity
EA UW Equity
EBAY UW Equity
ECL UN Equity
ED UN Equity
EFX UN Equity
EIX UN Equity
EL UN Equity
EMN UN Equity
EMR UN Equity
EOG UN Equity
EQIX UW Equity
EQR UN Equity
EQT UN Equity
ES UN Equity
ESRX UW Equity
ESS UN Equity
ETFC UW Equity
ETN UN Equity
ETR UN Equity
EVRG UN Equity
EW UN Equity
EXC UN Equity
EXPD UW Equity
EXPE UW Equity
EXR UN Equity
F UN Equity
FAST UW Equity
FB UW Equity
FBHS UN Equity
FCX UN Equity
FDX UN Equity
FE UN Equity
FFIV UW Equity
FIS UN Equity
FISV UW Equity
FITB UW Equity
FL UN Equity
FLIR UW Equity
FLR UN Equity
FLS UN Equity
FLT UN Equity
FMC UN Equity
FOX UW Equity
FOXA UW Equity
FRT UN Equity
FTI UN Equity
FTNT UW Equity
FTV UN Equity
GD UN Equity
GE UN Equity
GILD UW Equity
GIS UN Equity
GLW UN Equity
GM UN Equity
GOOG UW Equity
GOOGL UW Equity
GPC UN Equity
GPN UN Equity
GPS UN Equity
GRMN UW Equity
GS UN Equity
GT UW Equity
GWW UN Equity
HAL UN Equity
HAS UW Equity
HBAN UW Equity
HBI UN Equity
HCA UN Equity
HCP UN Equity
HD UN Equity
HES UN Equity
HFC UN Equity
HIG UN Equity
HII UN Equity
HLT UN Equity
HOG UN Equity
HOLX UW Equity
HON UN Equity
HP UN Equity
HPE UN Equity
HPQ UN Equity
HRB UN Equity
HRL UN Equity
HRS UN Equity
HSIC UW Equity
HST UN Equity
HSY UN Equity
HUM UN Equity
IBM UN Equity
ICE UN Equity
IDXX UW Equity
IFF UN Equity
ILMN UW Equity
INCY UW Equity
INFO UW Equity
INTC UW Equity
INTU UW Equity
IP UN Equity
IPG UN Equity
IPGP UW Equity
IQV UN Equity
IR UN Equity
IRM UN Equity
ISRG UW Equity
IT UN Equity
ITW UN Equity
IVZ UN Equity
JBHT UW Equity
JCI UN Equity
JEC UN Equity
JEF UN Equity
JNJ UN Equity
JNPR UN Equity
JPM UN Equity
JWN UN Equity
K UN Equity
KEY UN Equity
KHC UW Equity
KIM UN Equity
KLAC UW Equity
KMB UN Equity
KMI UN Equity
KMX UN Equity
KO UN Equity
KORS UN Equity
KR UN Equity
KSS UN Equity
KSU UN Equity
L UN Equity
LB UN Equity
LEG UN Equity
LEN UN Equity
LH UN Equity
LKQ UW Equity
LLL UN Equity
LLY UN Equity
LMT UN Equity
LNC UN Equity
LNT UN Equity
LOW UN Equity

LRCX UW Equity
LUV UN Equity
LYB UN Equity
M UN Equity
MA UN Equity
MAA UN Equity
MAC UN Equity
MAR UW Equity
MAS UN Equity
MAT UW Equity
MCD UN Equity
MCHP UW Equity
MCK UN Equity
MCO UN Equity
MDLZ UW Equity
MDT UN Equity
MET UN Equity
MGM UN Equity
MHK UN Equity
MKC UN Equity
MLM UN Equity
MMC UN Equity
MMM UN Equity
MNST UW Equity
MO UN Equity
MOS UN Equity
MPC UN Equity
MRK UN Equity
MRO UN Equity
MS UN Equity
MSCI UN Equity
MSFT UW Equity
MSI UN Equity
MTB UN Equity
MTD UN Equity
MU UW Equity
MYL UW Equity
NBL UN Equity
NCLH UN Equity
NDAQ UW Equity
NEE UN Equity
NEM UN Equity
NFLX UW Equity
NFX UN Equity
NI UN Equity
NKE UN Equity
NKTR UW Equity
NLSN UN Equity
NOC UN Equity
NOV UN Equity
NRG UN Equity
NSC UN Equity
NTAP UW Equity
NTRS UW Equity
NUE UN Equity
NVDA UW Equity
NWL UN Equity
NWS UW Equity
NWSA UW Equity
O UN Equity
OKE UN Equity
OMC UN Equity
ORCL UN Equity
ORLY UW Equity
OXY UN Equity
PAYX UW Equity
PBCT UW Equity
PCAR UW Equity
PCG UN Equity
PEG UN Equity
PEP UW Equity
PFE UN Equity
PFG UW Equity
PG UN Equity
PGR UN Equity
PH UN Equity
PHM UN Equity
PKG UN Equity
PKI UN Equity
PLD UN Equity
PM UN Equity
PNC UN Equity
PNR UN Equity
PNW UN Equity
PPG UN Equity
PPL UN Equity
PRGO UN Equity
PRU UN Equity
PSA UN Equity
PSX UN Equity
PVH UN Equity
PWR UN Equity
PX UN Equity
PXD UN Equity
PYPL UW Equity
QCOM UW Equity
QRVO UW Equity
RCL UN Equity
RE UN Equity
REG UN Equity
REGN UW Equity
RF UN Equity
RHI UN Equity
RHT UN Equity
RJF UN Equity
RL UN Equity
RMD UN Equity
ROK UN Equity
ROL UN Equity
ROP UN Equity
ROST UW Equity
RSG UN Equity
RTN UN Equity
SBAC UW Equity
SBUX UW Equity
SCG UN Equity
SCHW UN Equity
SEE UN Equity
SHW UN Equity
SIVB UW Equity
SJM UN Equity
SLB UN Equity
SLG UN Equity
SNA UN Equity
SNPS UW Equity
SO UN Equity
SPG UN Equity
SPGI UN Equity
SRCL UW Equity
SRE UN Equity
STI UN Equity
STT UN Equity
STX UW Equity
STZ UN Equity
SWK UN Equity
SWKS UW Equity
SYF UN Equity
SYK UN Equity
SYMC UW Equity
SYY UN Equity
T UN Equity
TAP UN Equity
TDG UN Equity
TEL UN Equity
TGT UN Equity
TIF UN Equity
TJX UN Equity
TMK UN Equity
TMO UN Equity
TPR UN Equity
TRIP UW Equity
TROW UW Equity
TRV UN Equity
TSCO UW Equity
TSN UN Equity
TSS UN Equity
TTWO UW Equity
TWTR UN Equity
TXN UW Equity
TXT UN Equity
UA UN Equity
UAA UN Equity
UAL UW Equity
UDR UN Equity
UHS UN Equity
ULTA UW Equity
UNH UN Equity
UNM UN Equity
UNP UN Equity
UPS UN Equity
URI UN Equity
USB UN Equity
UTX UN Equity
V UN Equity
VAR UN Equity
VFC UN Equity
VIAB UW Equity
VLO UN Equity
VMC UN Equity
VNO UN Equity
VRSK UW Equity
VRSN UW Equity
VRTX UW Equity
VTR UN Equity
VZ UN Equity
WAT UN Equity
WBA UW Equity
WCG UN Equity
WDC UW Equity
WEC UN Equity
WELL UN Equity
WFC UN Equity
WHR UN Equity
WLTW UW Equity
WM UN Equity
WMB UN Equity
WMT UN Equity
WRK UN Equity
WU UN Equity
WY UN Equity
WYNN UW Equity
XEC UN Equity
XEL UW Equity
XLNX UW Equity
XOM UN Equity
XRAY UW Equity
XRX UN Equity
XYL UN Equity
YUM UN Equity
ZBH UN Equity
ZION UW Equity
ZTS UN Equity
                                   Date  A UN Equity  AAL UW Equity  \
2018-04-02 09:30:00 2018-04-02 09:30:00        66.92          51.41
2018-04-02 09:45:00 2018-04-02 09:45:00        66.11          51.21
2018-04-02 10:00:00 2018-04-02 10:00:00        65.85          50.83
2018-04-02 10:15:00 2018-04-02 10:15:00        65.82          50.78
2018-04-02 10:30:00 2018-04-02 10:30:00        65.81          50.57
...                                 ...          ...            ...
2018-10-15 14:30:00 2018-10-15 14:30:00        66.20          32.13
2018-10-15 14:45:00 2018-10-15 14:45:00        66.20          32.18
2018-10-15 15:00:00 2018-10-15 15:00:00        65.96          32.08
2018-10-15 15:15:00 2018-10-15 15:15:00        65.83          32.07
2018-10-15 15:30:00 2018-10-15 15:30:00        65.88          31.98

                     AAP UN Equity  AAPL UW Equity  ABBV UN Equity  \
2018-04-02 09:30:00         118.13          168.42           93.95
2018-04-02 09:45:00         118.05          167.92           92.88
2018-04-02 10:00:00         117.13          167.55           92.56
2018-04-02 10:15:00         116.51          167.46           92.70
2018-04-02 10:30:00         115.97          167.32           92.72
...                            ...             ...             ...
2018-10-15 14:30:00         168.09          218.78           89.71
2018-10-15 14:45:00         168.48          219.17           89.93
2018-10-15 15:00:00         167.75          218.61           89.86
2018-10-15 15:15:00         167.63          218.23           89.66
2018-10-15 15:30:00         167.59          218.17           89.48

                     ABC UN Equity  ABMD UW Equity  ABT UN Equity  \
2018-04-02 09:30:00          86.10          288.83          59.93
2018-04-02 09:45:00          85.65          283.01          59.72
2018-04-02 10:00:00          84.65          282.14          59.55
2018-04-02 10:15:00          84.55          279.42          59.37
2018-04-02 10:30:00          84.28          282.05          59.37
...                            ...             ...            ...
2018-10-15 14:30:00          90.20          375.32          69.21
2018-10-15 14:45:00          90.18          374.92          69.26
2018-10-15 15:00:00          89.82          373.68          69.14
2018-10-15 15:15:00          89.73          373.85          68.95
2018-10-15 15:30:00          89.79          373.77          68.96

                     ACN UN Equity  ...  XEL UW Equity  XLNX UW Equity  \
2018-04-02 09:30:00         150.09  ...          45.76           71.85
2018-04-02 09:45:00         149.59  ...          45.60           71.69
2018-04-02 10:00:00         149.48  ...          45.62           71.30
2018-04-02 10:15:00         149.44  ...          45.68           71.08
2018-04-02 10:30:00         149.02  ...          45.44           71.27
...                            ...  ...            ...             ...
2018-10-15 14:30:00         158.94  ...          48.05           76.10
2018-10-15 14:45:00         159.09  ...          47.96           76.05
2018-10-15 15:00:00         158.55  ...          47.82           75.84
2018-10-15 15:15:00         158.33  ...          47.82           75.79
2018-10-15 15:30:00         158.32  ...          47.79           75.78

                     XOM UN Equity  XRAY UW Equity  XRX UN Equity  \
2018-04-02 09:30:00         74.390           50.12          28.74
2018-04-02 09:45:00         74.120           49.82          28.73
2018-04-02 10:00:00         73.690           49.67          28.40
2018-04-02 10:15:00         73.980           49.77          28.48
2018-04-02 10:30:00         73.820           49.76          28.35
...                            ...             ...            ...
2018-10-15 14:30:00         81.355           36.56          25.94
2018-10-15 14:45:00         81.510           36.43          26.01
2018-10-15 15:00:00         81.240           36.34          25.94
2018-10-15 15:15:00         81.090           36.34          25.91
2018-10-15 15:30:00         81.020           36.27          25.89

                     XYL UN Equity  YUM UN Equity  ZBH UN Equity  \
2018-04-02 09:30:00          76.87          85.77        109.290
2018-04-02 09:45:00          76.45          85.60        108.705
2018-04-02 10:00:00          76.17          85.22        108.400
2018-04-02 10:15:00          76.19          85.31        108.320
2018-04-02 10:30:00          76.14          85.03        108.590
...                            ...            ...            ...
2018-10-15 14:30:00          70.04          89.00        124.660
2018-10-15 14:45:00          70.10          89.06        124.550
2018-10-15 15:00:00          69.88          88.81        124.000
2018-10-15 15:15:00          69.87          88.75        123.720
2018-10-15 15:30:00          69.93          88.80        123.750

                     ZION UW Equity  ZTS UN Equity
2018-04-02 09:30:00           52.55          83.09
2018-04-02 09:45:00           52.52          82.96
2018-04-02 10:00:00           52.30          82.56
2018-04-02 10:15:00           52.13          82.51
2018-04-02 10:30:00           52.05          82.47
...                             ...            ...
2018-10-15 14:30:00           48.27          90.52
2018-10-15 14:45:00           48.43          90.52
2018-10-15 15:00:00           48.29          90.27
2018-10-15 15:15:00           48.26          90.04
2018-10-15 15:30:00           48.21          90.19

[3577 rows x 506 columns]

In [31]:
dt= pd.read_excel("Book2_yyy.xlsx")

In [17]:
dt=dt.drop([0])

SyntaxError: unexpected EOF while parsing (<ipython-input-17-a46dce8e412e>, line 2)

In [20]:
dt.index = range(len(dt))

In [24]:
dt=dt.drop([0,1])

In [26]:
dt.index = range(len(dt))

In [29]:
dt=dt.drop([len(df)-1])
dt = dt.drop([len(df) - 1])

KeyError: '[3575] not found in axis'

In [30]:
dt

,BarTp,Trade,Unnamed: 2,BarTp.1,Trade.1,Unnamed: 5,BarTp.2,Trade.2,Unnamed: 8,BarTp.3,...,Trade.501,Unnamed: 1505,BarTp.502,Trade.502,Unnamed: 1508,BarTp.503,Trade.503,Unnamed: 1511,BarTp.504,Trade.504
0,2018-04-02 09:30:00,66.92,NaN,2018-04-02 09:30:00,51.41,NaN,2018-04-02 09:30:00,118.13,NaN,2018-04-02 09:30:00,...,85.77,NaN,2018-04-02 09:30:00,109.29,NaN,2018-04-02 09:30:00,52.55,NaN,2018-04-02 09:30:00,83.09
1,2018-04-02 09:45:00,66.11,NaN,2018-04-02 09:45:00,51.21,NaN,2018-04-02 09:45:00,118.05,NaN,2018-04-02 09:45:00,...,85.6,NaN,2018-04-02 09:45:00,108.705,NaN,2018-04-02 09:45:00,52.52,NaN,2018-04-02 09:45:00,82.96
2,2018-04-02 10:00:00,65.85,NaN,2018-04-02 10:00:00,50.83,NaN,2018-04-02 10:00:00,117.13,NaN,2018-04-02 10:00:00,...,85.22,NaN,2018-04-02 10:00:00,108.4,NaN,2018-04-02 10:00:00,52.3,NaN,2018-04-02 10:00:00,82.56
3,2018-04-02 10:15:00,65.82,NaN,2018-04-02 10:15:00,50.78,NaN,2018-04-02 10:15:00,116.51,NaN,2018-04-02 10:15:00,...,85.31,NaN,2018-04-02 10:15:00,108.32,NaN,2018-04-02 10:15:00,52.13,NaN,2018-04-02 10:15:00,82.51
4,2018-04-02 10:30:00,65.81,NaN,2018-04-02 10:30:00,50.57,NaN,2018-04-02 10:30:00,115.97,NaN,2018-04-02 10:30:00,...,85.03,NaN,2018-04-02 10:30:00,108.59,NaN,2018-04-02 10:30:00,52.05,NaN,2018-04-02 10:30:00,82.47
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3571,2018-10-15 14:15:00,65.93,NaN,2018-10-15 14:15:00,31.93,NaN,2018-10-15 14:15:00,167.57,NaN,2018-10-15 14:15:00,...,88.72,NaN,NaN,NaN,NaN,2018-10-15 14:15:00,48.13,NaN,2018-10-15 14:15:00,90.21
3572,2018-10-15 14:30:00,66.2,NaN,2018-10-15 14:30:00,32.13,NaN,2018-10-15 14:30:00,168.09,NaN,2018-10-15 14:30:00,...,89,NaN,NaN,NaN,NaN,2018-10-15 14:30:00,48.27,NaN,2018-10-15 14:30:00,90.52
3573,2018-10-15 14:45:00,66.2,NaN,2018-10-15 14:45:00,32.18,NaN,2018-10-15 14:45:00,168.48,NaN,2018-10-15 14:45:00,...,89.06,NaN,NaN,NaN,NaN,2018-10-15 14:45:00,48.43,NaN,2018-10-15 14:45:00,90.52
3574,2018-10-15 15:00:00,65.96,NaN,2018-10-15 15:00:00,32.08,NaN,2018-10-15 15:00:00,167.75,NaN,2018-10-15 15:00:00,...,88.81,NaN,NaN,NaN,NaN,2018-10-15 15:00:00,48.29,NaN,2018-10-15 15:00:00,90.27
3577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN